pipeline {
    agent any 

    tools {
        maven 'Maven 3.6.3' 
        jdk 'JDK 11'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/username/my_project.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean install'
            }

            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                    jacoco execPattern: '**/target/jacoco.exec'
                }
            }
        }
    }
}
