pipeline {
    agent any 

    tools {
        maven 'Maven 3.6.3' 
        jdk 'JDK 11'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/llvllj/ci-cd-ma1.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean install'
            }

            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                    jacoco execPattern: '**/target/jacoco.exec'
                }
            }
        }

        stage('Codacy Analysis') {
            steps {
                sh 'mvn jacoco:report'
                codacy(
                    pattern: '**/target/site/jacoco/jacoco.xml',
                    projectToken: 'llvllj-project',
                    failOnNewCoverage: true
                )
            }
        }
    }
}
